version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports: 
    - "5432:5432"
    environment:
      POSTGRES_USER: timestack
      POSTGRES_PASSWORD: timestack
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      resources: 
        limits:
          cpus: '0.20'
          memory: 500M
        reservations:
          cpus: '0.10'
          memory: 200M
volumes:
  postgres:
